/**
 * FlatBuffers Serializer
 *
 * Zero-copy serialization using FlatBuffers.
 * Provides both static (schema-compiled) and dynamic approaches.
 */

import { Builder, ByteBuffer } from 'flatbuffers';
import { ok, err } from '@servicejs/result';
import type { Serializer } from './serializer.js';
import { serializationError } from './serializer.js';

/**
 * FlatBuffers schema interface
 *
 * Defines how to encode/decode data using FlatBuffers.
 * Typically, you'd use generated code from flatc compiler.
 */
export interface FlatBuffersSchema<T> {
  /**
   * Encode a value into a FlatBuffers builder
   * @param builder - FlatBuffers builder
   * @param value - Value to encode
   * @returns Offset of the encoded value
   */
  encode(builder: Builder, value: T): number;

  /**
   * Decode a value from a ByteBuffer
   * @param buffer - FlatBuffers ByteBuffer
   * @returns Decoded value
   */
  decode(buffer: ByteBuffer): T;

  /**
   * Get the root object from a ByteBuffer at given offset
   * @param buffer - FlatBuffers ByteBuffer
   * @param offset - Offset of the root object
   * @returns Root object
   */
  getRootAs?(buffer: ByteBuffer, offset?: number): any;
}

/**
 * FlatBuffers serializer options
 */
export interface FlatBuffersSerializerOptions {
  /**
   * Initial builder size
   * Default: 1024
   */
  initialSize?: number;
}

/**
 * Create a FlatBuffers serializer from a schema
 *
 * FlatBuffers is a zero-copy serialization library optimized for performance.
 * Requires pre-compiled schemas generated by the flatc compiler.
 *
 * **Pros:**
 * - Zero-copy deserialization (extremely fast reads)
 * - Very compact binary format
 * - Random access without parsing
 * - Schema evolution support
 * - Cross-language compatibility
 *
 * **Cons:**
 * - Requires schema compilation step
 * - More complex than JSON/MessagePack
 * - Write performance is moderate
 * - Limited dynamic usage
 *
 * @param schema - FlatBuffers schema implementation
 * @param options - Serializer options
 * @returns FlatBuffers serializer
 *
 * @example
 * ```typescript
 * // Assuming you have generated FlatBuffers schema code:
 * import { Message } from './message_generated.js';
 *
 * const schema: FlatBuffersSchema<MessageData> = {
 *   encode(builder, value) {
 *     const typeOffset = builder.createString(value.type);
 *     Message.startMessage(builder);
 *     Message.addType(builder, typeOffset);
 *     Message.addValue(builder, value.value);
 *     return Message.endMessage(builder);
 *   },
 *   decode(buffer) {
 *     const msg = Message.getRootAsMessage(buffer);
 *     return {
 *       type: msg.type(),
 *       value: msg.value(),
 *     };
 *   },
 * };
 *
 * const serializer = createFlatBuffersSerializer(schema);
 * ```
 */
export const createFlatBuffersSerializer = <T>(
  schema: FlatBuffersSchema<T>,
  options: FlatBuffersSerializerOptions = {}
): Serializer<T> => {
  const initialSize = options.initialSize ?? 1024;

  return {
    format: 'flatbuffers',

    serialize(value: T) {
      try {
        const builder = new Builder(initialSize);
        const offset = schema.encode(builder, value);
        builder.finish(offset);

        const bytes = builder.asUint8Array();
        return ok(bytes);
      } catch (error) {
        return err(
          serializationError(
            `Failed to serialize with FlatBuffers: ${error instanceof Error ? error.message : String(error)}`,
            'SERIALIZE_FAILED',
            error
          )
        );
      }
    },

    deserialize(data: Uint8Array) {
      try {
        const buffer = new ByteBuffer(data);
        const value = schema.decode(buffer);
        return ok(value);
      } catch (error) {
        return err(
          serializationError(
            `Failed to deserialize FlatBuffers data: ${error instanceof Error ? error.message : String(error)}`,
            'DESERIALIZE_FAILED',
            error
          )
        );
      }
    },
  };
};

/**
 * Dynamic FlatBuffers schema builder
 *
 * Allows creating simple FlatBuffers schemas at runtime without compilation.
 * Limited to basic types and flat structures.
 *
 * **Limitations:**
 * - No nested tables (use vectors of structs instead)
 * - No unions
 * - No advanced features
 * - Performance not as good as compiled schemas
 *
 * Use compiled schemas for production. This is mainly for prototyping.
 *
 * @example
 * ```typescript
 * const schema = createDynamicFlatBuffersSchema<{
 *   id: number;
 *   name: string;
 *   active: boolean;
 * }>({
 *   fields: [
 *     { name: 'id', type: 'number' },
 *     { name: 'name', type: 'string' },
 *     { name: 'active', type: 'boolean' },
 *   ],
 * });
 *
 * const serializer = createFlatBuffersSerializer(schema);
 * ```
 */
export type DynamicFieldType = 'number' | 'string' | 'boolean' | 'bytes';

export interface DynamicField {
  name: string;
  type: DynamicFieldType;
}

export interface DynamicSchemaConfig {
  fields: DynamicField[];
}

/**
 * Create a dynamic FlatBuffers schema from a configuration
 *
 * @param config - Schema configuration
 * @returns FlatBuffers schema
 */
export const createDynamicFlatBuffersSchema = <T extends Record<string, any>>(
  config: DynamicSchemaConfig
): FlatBuffersSchema<T> => {
  return {
    encode(builder: Builder, value: T): number {
      // Pre-create strings and byte arrays
      const stringOffsets: Record<string, number> = {};
      for (const field of config.fields) {
        if (field.type === 'string' && typeof value[field.name] === 'string') {
          stringOffsets[field.name] = builder.createString(value[field.name]);
        }
      }

      // Start table
      builder.startObject(config.fields.length);

      // Add fields in reverse order (FlatBuffers requirement)
      for (let i = config.fields.length - 1; i >= 0; i--) {
        const field = config.fields[i];
        if (!field) continue;

        const val = value[field.name];

        switch (field.type) {
          case 'number':
            if (typeof val === 'number') {
              builder.addFieldFloat64(i, val, 0);
            }
            break;
          case 'string':
            const offset = stringOffsets[field.name];
            if (offset !== undefined) {
              builder.addFieldOffset(i, offset, 0);
            }
            break;
          case 'boolean':
            if (typeof val === 'boolean') {
              builder.addFieldInt8(i, val ? 1 : 0, 0);
            }
            break;
        }
      }

      return builder.endObject();
    },

    decode(buffer: ByteBuffer): T {
      const result: any = {};
      const table = buffer.readInt32(buffer.position()) + buffer.position();

      for (let i = 0; i < config.fields.length; i++) {
        const field = config.fields[i];
        if (!field) continue;

        const vtableOffset = buffer.readInt16(table - buffer.readInt32(table) + 4 + i * 2);

        if (vtableOffset === 0) continue;

        const fieldOffset = table + vtableOffset;

        switch (field.type) {
          case 'number':
            result[field.name] = buffer.readFloat64(fieldOffset);
            break;
          case 'string':
            const stringOffset = buffer.readInt32(fieldOffset) + fieldOffset;
            const length = buffer.readInt32(stringOffset);
            const bytes = buffer.bytes();
            result[field.name] = new TextDecoder().decode(bytes.subarray(stringOffset + 4, stringOffset + 4 + length));
            break;
          case 'boolean':
            result[field.name] = buffer.readInt8(fieldOffset) !== 0;
            break;
        }
      }

      return result as T;
    },
  };
};
