/**
 * Generate Cap'n Proto TypeScript code from schemas
 *
 * This script generates optimized TypeScript classes from Cap'n Proto schemas
 * for the benchmark. Generated classes provide direct memory access without
 * runtime interpretation overhead.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { createCapnpSchema } from '../src/capnp.js';
import { generateCapnpClass } from '../src/capnp-codegen.js';

// ============================================================================
// Schema Definitions
// ============================================================================

// User schema (nested in ComplexMessage)
const userSchema = createCapnpSchema({
  name: 'User',
  fields: [
    { name: 'id', type: 'uint32', slot: 0 },
    { name: 'name', type: 'text', slot: 0 },
    { name: 'email', type: 'text', slot: 1 },
    { name: 'role', type: 'text', slot: 2 },
  ],
});

// Metadata schema (nested in ComplexMessage)
const metadataSchema = createCapnpSchema({
  name: 'Metadata',
  fields: [
    { name: 'source', type: 'text', slot: 0 },
    { name: 'priority', type: 'uint32', slot: 0 },
    { name: 'flags', type: { kind: 'list', elementType: 'bool' }, slot: 1 },
  ],
});

// Simple Message Schema
const simpleCapnpSchema = createCapnpSchema({
  name: 'SimpleMessage',
  fields: [
    { name: 'id', type: 'uint32', slot: 0 },
    { name: 'name', type: 'text', slot: 0 },
    { name: 'active', type: 'bool', slot: 4 },
    { name: 'score', type: 'float64', slot: 8 },
  ],
});

// Complex Message Schema
const complexCapnpSchema = createCapnpSchema({
  name: 'ComplexMessage',
  fields: [
    { name: 'id', type: 'uint32', slot: 0 },
    { name: 'timestamp', type: 'uint64', slot: 8 },
    { name: 'user', type: { kind: 'struct', schema: userSchema }, slot: 0 },
    { name: 'tags', type: { kind: 'list', elementType: 'text' }, slot: 1 },
    { name: 'metadata', type: { kind: 'struct', schema: metadataSchema }, slot: 2 },
  ],
});

// Large Message Schema
const largeCapnpSchema = createCapnpSchema({
  name: 'LargeMessage',
  fields: [
    { name: 'id', type: 'uint32', slot: 0 },
    { name: 'coordinates', type: { kind: 'list', elementType: 'float64' }, slot: 0 },
    { name: 'labels', type: { kind: 'list', elementType: 'text' }, slot: 1 },
    { name: 'matrix', type: { kind: 'list', elementType: { kind: 'list', elementType: 'float64' } }, slot: 2 },
  ],
});

// ============================================================================
// Generator
// ============================================================================

const main = () => {
  console.log('🔨 Generating Cap\'n Proto TypeScript code...\n');

  // Create output directory
  const outputDir = join(process.cwd(), 'src', 'capnp-generated');
  mkdirSync(outputDir, { recursive: true });
  console.log(`📁 Output directory: ${outputDir}\n`);

  // Generate code for each schema
  const schemas = [
    { name: 'User', schema: userSchema },
    { name: 'Metadata', schema: metadataSchema },
    { name: 'SimpleMessage', schema: simpleCapnpSchema },
    { name: 'ComplexMessage', schema: complexCapnpSchema },
    { name: 'LargeMessage', schema: largeCapnpSchema },
  ];

  for (const { name, schema } of schemas) {
    console.log(`📝 Generating ${name}...`);

    try {
      const generatedCode = generateCapnpClass(schema);
      const filename = join(outputDir, `${name}.ts`);
      writeFileSync(filename, generatedCode, 'utf-8');
      console.log(`   ✅ Written to ${name}.ts`);
    } catch (error) {
      console.error(`   ❌ Error generating ${name}:`, error);
    }
  }

  // Generate index file that exports all schemas
  console.log('\n📝 Generating index.ts...');
  const indexContent = `/**
 * Generated Cap'n Proto TypeScript classes
 *
 * Auto-generated by scripts/generate-capnp.ts
 * DO NOT EDIT MANUALLY
 */

export { User } from './User.js';
export { Metadata } from './Metadata.js';
export { SimpleMessage } from './SimpleMessage.js';
export { ComplexMessage } from './ComplexMessage.js';
export { LargeMessage } from './LargeMessage.js';

// Schema exports for use in generated code
export { UserSchema } from '../capnp.js';
export { MetadataSchema } from '../capnp.js';
`;

  writeFileSync(join(outputDir, 'index.ts'), indexContent, 'utf-8');
  console.log('   ✅ Written to index.ts');

  console.log('\n✨ Generation complete!\n');
};

main();
