/**
 * Generated Cap'n Proto TypeScript classes
 *
 * Auto-generated by scripts/generate-capnp.ts
 * DO NOT EDIT MANUALLY
 */

export { User } from './User.js';
export { Metadata } from './Metadata.js';
export { SimpleMessage } from './SimpleMessage.js';
export { ComplexMessage } from './ComplexMessage.js';
export { LargeMessage } from './LargeMessage.js';

// Schema exports for use in generated code
export { UserSchema } from '../capnp.js';
export { MetadataSchema } from '../capnp.js';
